export enum rejectionCause {
  NAMESPACE_NOT_FOUND = 'NAMESPACE_NOT_FOUND',
  TOPIC_NOT_MATCHING = 'TOPIC_NOT_MATCHING',
  URL_NOT_FOUND = 'URL_NOT_FOUND',
  URL_FORMAT_ERROR = 'URL_FORMAT_ERROR',
  URL_MISSING_TEMPLATE_REPLACEMENT = 'URL_MISSING_TEMPLATE_REPLACEMENT',
}
